import { Effect } from 'effect';
import { Application } from 'effective-rsc';

import './styles.css';

const ERSC = Application.ersc();

const RootLayout = ERSC.Layout.make({
  render: ({ children }) =>
    Effect.succeed(
      <html lang='en'>
        <head>
          <title>effective-rsc application</title>
          <link rel='icon' href='/favicon.svg' type='image/svg+xml' />
          <meta name='description' content='Generated by create-ersc-app.' />
        </head>
        <body className='bg-paper text-ink min-h-screen antialiased'>{children}</body>
      </html>,
    ),
});

const HomePage = ERSC.Page.make({
  render: () =>
    Effect.succeed(
      <main className='mx-auto flex min-h-screen w-full max-w-2xl flex-col justify-center px-6 py-24'>
        <svg aria-hidden='true' className='size-12' viewBox='0 0 64 64'>
          <rect x='16' y='27.5' width='26' height='9' rx='4.5' fill='var(--accent)' />
          <rect x='16' y='11' width='9' height='42' rx='4.5' fill='var(--ink)' />
          <rect x='16' y='11' width='32' height='9' rx='4.5' fill='var(--ink)' />
          <rect x='16' y='44' width='32' height='9' rx='4.5' fill='var(--ink)' />
        </svg>

        <h1 className='mt-8 text-4xl font-semibold tracking-tight text-balance sm:text-5xl'>
          Your application is ready.
        </h1>

        <p className='text-muted mt-4 text-lg'>
          Edit <code className='text-accent'>src/application.tsx</code> to start building.
        </p>

        <p className='text-muted mt-12 text-sm'>
          Documentation is installed at <code>node_modules/effective-rsc/docs</code>.
        </p>
      </main>,
    ),
});

export default ERSC.make({
  routes: ERSC.Routes.make({ layout: RootLayout }).page('/', HomePage),
});
